version: '3.2'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
    hostname: elasticsearch
    restart: always
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: bind
        source: ./elasticsearch/config/fullchain.pem
        target: /usr/share/elasticsearch/config/fullchain.pem
        read_only: true
      - type: bind
        source: ./elasticsearch/config/privkey.pem
        target: /usr/share/elasticsearch/config/privkey.pem
        read_only: true
      - type: bind
        source: ./elasticsearch/data
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
#      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx12G -Xms256m -XX:+UnlockDiagnosticVMOptions -Xlog:gc+heap+coops=info"
      ELASTIC_PASSWORD: EVKjaNKfJkoG11vWyqUD
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    networks:
      elk:
        aliases:
          - elasticsearch
      proxy:
        aliases:
          - elasticsearch
  logstash:
    image: docker.elastic.co/logstash/logstash:7.4.2
    restart: always
    volumes:
      - type: bind
        source: ./logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
    hostname: logstash
    ports:
      - "127.0.0.1:5044:5044"
      - "127.0.0.1:5514:5514"
#      - "9600:9600"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    environment:
      LS_JAVA_OPTS: "-Xmx2G -Xms256m -XX:+UnlockDiagnosticVMOptions -Xlog:gc+heap+coops=info"
    networks:
      - elk
      - logstash
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:7.4.2
    restart: always
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
      - type: bind
        source: ./kibana/config/fullchain.pem
        target: /usr/share/kibana/config/fullchain.pem
        read_only: true
      - type: bind
        source: ./kibana/config/privkey.pem
        target: /usr/share/kibana/config/privkey.pem
        read_only: true
    ports:
      - "5601:5601"
    hostname: kibana
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    networks:
      elk:
        aliases:
          - kibana
      proxy:
        aliases:
          - kibana
    depends_on:
      - elasticsearch

  cerebro:
    image: lmenezes/cerebro:latest
     ports:
       9000:9000
    hostname: cerebro
    restart: always
    networks:
      elk:
      proxy:
        aliases:
          - cerebro
    depends_on:
      - elasticsearch

networks:
  elk:
    driver: bridge
  logstash:
    driver: bridge
#  proxy:
#   external:
#     name: apacheproxy
  proxy:
    driver: bridge